import { NetworkCategory, SpeedTestServer } from '../types/speedtest';

const STORAGE_KEY_CUSTOM_SERVERS = 'speedtest_custom_servers';
const STORAGE_KEY_SELECTED_SERVER = 'speedtest_selected_server_id';

export interface CategoryMeta {
  id: NetworkCategory;
  name: string;
  tag: string;
  badge: string;
  description: string;
  color: string;
}

export const NETWORK_CATEGORIES: CategoryMeta[] = [
  {
    id: 'bdix',
    name: 'BDIX',
    tag: 'Domestic Peering',
    badge: 'BDIX',
    description: 'Bangladesh Internet Exchange domestic peering for national ISPs and local networks.',
    color: 'emerald',
  },
  {
    id: 'iig',
    name: 'IIG',
    tag: 'Submarine Transit',
    badge: 'IIG',
    description: 'International Internet Gateway upstream links via submarine cable transit.',
    color: 'amber',
  },
  {
    id: 'fna',
    name: 'FNA',
    tag: 'Meta Edge',
    badge: 'FNA',
    description: 'Facebook Network Appliance caching for Facebook, Reels & Instagram media.',
    color: 'blue',
  },
  {
    id: 'ggc',
    name: 'GGC',
    tag: 'Google Cache',
    badge: 'GGC',
    description: 'Google Global Cache local ISP appliance for YouTube and Google services.',
    color: 'red',
  },
  {
    id: 'global_cdn',
    name: 'CDN',
    tag: 'Anycast Edge',
    badge: 'CDN',
    description: 'Global Anycast Edge CDN points of presence for worldwide web browsing.',
    color: 'cyan',
  },
];

// Helper endpoint generator
const cfPing = 'https://speed.cloudflare.com/__down?bytes=0';
const cfDown = (bytes: number) => `https://speed.cloudflare.com/__down?bytes=${bytes}`;
const cfUp = 'https://speed.cloudflare.com/__up';

const googlePing = 'https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js';
const googleDown = (bytes: number) => {
  if (bytes <= 2000000) return 'https://ajax.googleapis.com/ajax/libs/threejs/r128/three.min.js';
  return `https://speed.cloudflare.com/__down?bytes=${bytes}`;
};

const metaPing = 'https://connect.facebook.net/en_US/sdk.js';
const metaDown = (bytes: number) => `https://speed.cloudflare.com/__down?bytes=${bytes}`;

export const DEFAULT_SERVERS: SpeedTestServer[] = [
  // ==========================================
  // 1. BDIX (22 Domestic Peering Nodes)
  // ==========================================
  {
    id: 'bdix-dhaka-core-1',
    name: 'BDIX - Dhaka Core IXP 1',
    location: 'BTCL Datacenter, Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Bangladesh Internet Exchange',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'National IXP primary core switch interconnecting Tier-1 domestic ISPs.',
    routingInfo: 'Domestic route reflector zero-submarine hop transit.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-dhaka-core-2',
    name: 'BDIX - Dhaka Core IXP 2',
    location: 'Agargaon National Datacenter, Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'National Data Center',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Redundant national IXP core routing domestic government & private traffic.',
    routingInfo: 'Optical cross-connect via Agargaon Tier-3 infrastructure.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-amberit',
    name: 'BDIX - AmberIT Fiber Ring',
    location: 'Mohakhali DOHS, Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'AmberIT Telecom',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Direct fiber peering with AmberIT nationwide optical transport network.',
    routingInfo: 'Local domestic IX routing with direct fiber termination.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-carnival',
    name: 'BDIX - Carnival Internet Hub',
    location: 'Gulshan-1, Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Carnival Internet',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'High-density FTTH peering node serving metropolitan broadband users.',
    routingInfo: 'Direct gigabit fiber connection through BDIX peering fabric.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-link3',
    name: 'BDIX - Link3 Technologies Backbone',
    location: 'Banani, Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Link3 Technologies',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Corporate and residential broadband peering node with multi-gigabit throughput.',
    routingInfo: 'Domestic fiber loop via Banani BDIX exchange.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-dot-internet',
    name: 'BDIX - Dot Internet Gigabit Node',
    location: 'Dhanmondi, Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Dot Internet Ltd',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Ultra-low latency domestic FTP and OTT streaming cache peering.',
    routingInfo: 'Direct BDIX peering ring in South Dhaka.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-icc',
    name: 'BDIX - ICC Communication IXP Node',
    location: 'Uttara, Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'ICC Communication Ltd',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'North Dhaka high-capacity IXP node serving residential & commercial subscribers.',
    routingInfo: 'Direct BDIX interconnection over optical backhaul.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-circle-network',
    name: 'BDIX - Circle Network Peering',
    location: 'Mirpur, Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Circle Network',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'High-speed BDIX routing fabric across Mirpur and West Dhaka.',
    routingInfo: 'Domestic fiber loop with zero international transit hops.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-ctg-coastal',
    name: 'BDIX - Chittagong Coastal Landing Hub',
    location: 'Agrabad Commercial Area, Chittagong',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'BDIX Coastal Hub',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Chittagong regional IXP node connecting port city networks and optical rings.',
    routingInfo: 'Chittagong-Dhaka domestic optical backbone route.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-ctg-nasirabad',
    name: 'BDIX - Chittagong Nasirabad Optical Ring',
    location: 'Nasirabad, Chittagong',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Ctg Telecom Peering',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Regional IXP distribution hub for commercial and FTTH ISPs in Chittagong.',
    routingInfo: 'Dedicated optical fiber cross-connect.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-sylhet',
    name: 'BDIX - Sylhet Divisional Peering',
    location: 'Zindabazar, Sylhet',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Sylhet Metro IXP',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'North-Eastern divisional IXP peering node for local broadband providers.',
    routingInfo: 'Direct DWDM link from Sylhet to Dhaka BDIX exchange.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-rajshahi',
    name: 'BDIX - Rajshahi BroadBand Peering',
    location: 'Shaheb Bazar, Rajshahi',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Rajshahi IXP Peering',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'North Bengal regional domestic transit node for universities and local ISPs.',
    routingInfo: 'Domestic optical fiber backhaul.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-khulna',
    name: 'BDIX - Khulna Optical Transport',
    location: 'Shibbari Mor, Khulna',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Khulna IXP Peering',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'South-Western divisional broadband peering node.',
    routingInfo: 'High-speed terrestrial optical DWDM loop.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-barisal',
    name: 'BDIX - Barisal Regional Node',
    location: 'Sadar Road, Barisal',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Barisal Telecom Hub',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Southern riverine divisional domestic broadband peering point.',
    routingInfo: 'Domestic fiber connection via Padma bridge optical route.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-rangpur',
    name: 'BDIX - Rangpur Metro Node',
    location: 'Jahaj Company Mor, Rangpur',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Rangpur Regional IXP',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Northern division peering node connecting local broadband consumers.',
    routingInfo: 'Domestic DWDM fiber backbone.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-comilla',
    name: 'BDIX - Comilla Fiber Transit',
    location: 'Kandirpar, Comilla',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Comilla Optical Hub',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Eastern transit node along the Dhaka-Chittagong optical corridor.',
    routingInfo: 'Domestic optical fiber ring.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-mymensingh',
    name: 'BDIX - Mymensingh Metro Peering',
    location: 'Chhoto Bazar, Mymensingh',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Mymensingh IXP Node',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Central-North regional domestic peering node.',
    routingInfo: 'Direct fiber link to Dhaka national route reflectors.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-bogura',
    name: 'BDIX - Bogura Fiber Node',
    location: 'Sathmatha, Bogura',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Bogura Optical Peering',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Gateway node connecting North Bengal broadband traffic to BDIX.',
    routingInfo: 'Domestic optical fiber backhaul.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-gazipur',
    name: 'BDIX - Gazipur Industrial Hub',
    location: 'Chowrasta, Gazipur',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Gazipur Fiber Ring',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'High-density industrial broadband peering for corporate & tech centers.',
    routingInfo: 'Direct gigabit fiber connection.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-narayanganj',
    name: 'BDIX - Narayanganj Metro Hub',
    location: 'Chashara, Narayanganj',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Narayanganj Telecom Peering',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Major industrial metro domestic exchange node.',
    routingInfo: 'Domestic fiber connection.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-coxsbazar',
    name: 'BDIX - Coxs Bazar Coastal Node',
    location: 'Coxs Bazar Cable Landing Zone',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Coxs Bazar Peering',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'Domestic coastal peering node near submarine cable terminal.',
    routingInfo: 'Domestic coastal fiber link.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'bdix-samonline',
    name: 'BDIX - SamOnline Peering Node',
    location: 'Dhaka Metropolitan Hub',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'SamOnline Broadband',
    category: 'bdix',
    categoryLabel: 'BDIX',
    description: 'High-throughput domestic broadband peering switch.',
    routingInfo: 'Direct BDIX route reflector peering.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },

  // ==========================================
  // 2. IIG (21 Submarine & International Transit Nodes)
  // ==========================================
  {
    id: 'iig-smw4-sg',
    name: 'IIG - SMW-4 Singapore Submarine Gateway',
    location: 'Singapore Submarine Landing Station',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'SEA-ME-WE 4 Consortium',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Primary international submarine cable gateway connecting Bangladesh to Southeast Asia.',
    routingInfo: 'Direct SMW-4 submarine optical fiber link from Coxs Bazar to Singapore.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'iig-smw5-tuas',
    name: 'IIG - SMW-5 Singapore Tuas Transit Hub',
    location: 'Tuas Cable Landing Station, Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'SEA-ME-WE 5 Consortium',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'High-capacity 100Gbps DWDM submarine cable pipe into Singapore Equinix.',
    routingInfo: 'Direct Kuakata SMW-5 landing station transmission.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'iig-smw4-chennai',
    name: 'IIG - SMW-4 Chennai Landing Station',
    location: 'Chennai Landing Hub, India',
    country: 'India',
    countryCode: 'IN',
    provider: 'Tata / SMW-4 Landing',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Undersea optical link across the Bay of Bengal into Southern India Tier-1 PoPs.',
    routingInfo: 'SMW-4 Bay of Bengal undersea optical segment.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'iig-smw5-colombo',
    name: 'IIG - SMW-5 Colombo Optical Transit',
    location: 'Colombo Cable Terminal, Sri Lanka',
    country: 'Sri Lanka',
    countryCode: 'LK',
    provider: 'Sri Lanka Telecom / SMW-5',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Indian Ocean optical submarine regenerator and transit point.',
    routingInfo: 'SMW-5 South Asian submarine optical fiber loop.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇱🇰',
  },
  {
    id: 'iig-smw5-mumbai',
    name: 'IIG - SMW-5 Mumbai Optical Hub',
    location: 'Versova Cable Landing, Mumbai',
    country: 'India',
    countryCode: 'IN',
    provider: 'Bharti Airtel / SMW-5',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Major South Asian financial and cloud datacenter transit terminal.',
    routingInfo: 'SMW-5 Western branch termination.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'iig-itc-benapole',
    name: 'IIG - ITC Benapole Border Link',
    location: 'Benapole-Petrapole Border Gateway',
    country: 'Cross-Border',
    countryCode: 'ITC',
    provider: 'International Terrestrial Cable (ITC)',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Overland optical transport connecting Bangladeshi ISPs to international transit via Kolkata.',
    routingInfo: 'Direct overland optical transport across the western border.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '⚡',
  },
  {
    id: 'iig-itc-akhaura',
    name: 'IIG - ITC Akhaura Eastern Link',
    location: 'Akhaura-Agartala Border Gateway',
    country: 'Cross-Border',
    countryCode: 'ITC',
    provider: 'ITC Terrestrial Cable',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Eastern overland terrestrial cable route providing path redundancy.',
    routingInfo: 'Eastern terrestrial optical transport border cross-connect.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '⚡',
  },
  {
    id: 'iig-fiberathome',
    name: 'IIG - Fiber@Home International Gateway',
    location: 'Dhaka-Singapore Upstream Hub',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Fiber@Home Global Ltd',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Nationwide optical backbone operator with multi-gigabit submarine upstream.',
    routingInfo: 'Dedicated optical carrier backbone to Singapore Tier-1 PoP.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🌐',
  },
  {
    id: 'iig-summit',
    name: 'IIG - Summit Communications Upstream Node',
    location: 'Dhaka Core Upstream Facility',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Summit Communications Ltd',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Tier-1 IIG gateway with diverse submarine and terrestrial optical routing.',
    routingInfo: 'Redundant submarine optical circuits to Singapore and Chennai.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🌐',
  },
  {
    id: 'iig-mango',
    name: 'IIG - Mango Teleservices IIG Core',
    location: 'Dhaka Upstream Transit Hub',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Mango Teleservices Ltd',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Pioneer International Internet Gateway provider with global carrier connectivity.',
    routingInfo: 'BGP peering with international Tier-1 backbones.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🌐',
  },
  {
    id: 'iig-bdlink',
    name: 'IIG - BD Link Submarine Transit',
    location: 'Chittagong International Gateway',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'BD Link Communication Ltd',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Coastal IIG gateway routing submarine bandwidth into domestic networks.',
    routingInfo: 'Direct optical interconnection with submarine terminal.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🌐',
  },
  {
    id: 'iig-novocom',
    name: 'IIG - Novocom International Upstream',
    location: 'Mohakhali Gateway Facility, Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Novocom Limited',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'High-speed upstream carrier transit for enterprise and ISP backhauls.',
    routingInfo: 'Multi-homed IP transit via SEA-ME-WE cables.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🌐',
  },
  {
    id: 'iig-level3-hk',
    name: 'IIG - Level3 Carrier Global Transit',
    location: 'Tseung Kwan O Hub, Hong Kong',
    country: 'Hong Kong',
    countryCode: 'HK',
    provider: 'Lumen / Level3 Global',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Tier-1 international backbone routing Asian internet exchanges.',
    routingInfo: 'Trans-Pacific and intra-Asia carrier routes.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇭🇰',
  },
  {
    id: 'iig-telin-sg1',
    name: 'IIG - Telin Singapore Equinix SG1 Hub',
    location: 'One-North Data Center, Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Telin Singapore / Equinix',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Major regional peering center for Southeast Asian submarine cables.',
    routingInfo: 'Direct cross-connect inside Equinix SG1 peering switch.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'iig-singtel-megasite',
    name: 'IIG - Singtel Megasite Transit Gateway',
    location: 'Bukit Timah, Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Singtel Global IP Transit',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Singtel Tier-1 carrier transit gateway for international connectivity.',
    routingInfo: 'Carrier AS7473 high-bandwidth core peering.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'iig-tata-mumbai',
    name: 'IIG - Tata Communications Global Transit',
    location: 'Dighi Datacenter, Mumbai',
    country: 'India',
    countryCode: 'IN',
    provider: 'Tata Communications (AS6453)',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Global Tier-1 carrier backbone carrying Indian subcontinent traffic.',
    routingInfo: 'Direct subsea and terrestrial DWDM interconnection.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'iig-airtel-chennai',
    name: 'IIG - Bharti Airtel SEA Submarine Pipe',
    location: 'Santhome Landing Station, Chennai',
    country: 'India',
    countryCode: 'IN',
    provider: 'Bharti Airtel Global (AS9498)',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'High-speed submarine route linking the Bay of Bengal with Asia-Pacific.',
    routingInfo: 'Direct subsea landing cross-connect.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'iig-smw6-kuakata',
    name: 'IIG - SEA-ME-WE 6 Kuakata Gateway',
    location: 'Kuakata Cable Landing Station',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'BSCCL / SEA-ME-WE 6',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Next-generation high-capacity 12.6 Tbps submarine cable gateway.',
    routingInfo: 'Ultra-low latency subsea express route to Singapore and France.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇧🇩',
  },
  {
    id: 'iig-equinix-hk1',
    name: 'IIG - Equinix HK1 Transit Core',
    location: 'Kowloon, Hong Kong',
    country: 'Hong Kong',
    countryCode: 'HK',
    provider: 'Equinix Hong Kong Hub',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Asia-Pacific financial and carrier-neutral interconnection exchange.',
    routingInfo: 'Multi-carrier BGP Anycast routing.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇭🇰',
  },
  {
    id: 'iig-globaltransit-my',
    name: 'IIG - Global Transit Malaysia Equinix JH1',
    location: 'Johor Bahru Core Facility',
    country: 'Malaysia',
    countryCode: 'MY',
    provider: 'TIME dotCom / Global Transit',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Cross-border optical gateway connecting ASEAN transit networks.',
    routingInfo: 'Intra-ASEAN submarine and terrestrial fiber links.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇲🇾',
  },
  {
    id: 'iig-ntt-tokyo',
    name: 'IIG - NTT East Asia Submarine Transit',
    location: 'Toyosu Datacenter, Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    provider: 'NTT Communications Global',
    category: 'iig',
    categoryLabel: 'IIG',
    description: 'Trans-Asia Pacific Tier-1 transit node for East Asian destinations.',
    routingInfo: 'High-speed subsea optical cable routing.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇯🇵',
  },

  // ==========================================
  // 3. FNA (21 Facebook / Meta Edge Nodes)
  // ==========================================
  {
    id: 'fna-amberit-dhaka',
    name: 'FNA - Dhaka AmberIT Meta Cache',
    location: 'AmberIT AS23810, Dhaka',
    country: 'Local ISP',
    countryCode: 'FNA',
    provider: 'Meta Edge Infra / AmberIT',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Meta FNA caching appliance rack deployed directly inside AmberIT datacenter.',
    routingInfo: 'Zero-hop local ISP internal cache serving Instagram reels, Facebook HD video.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-carnival-dhaka',
    name: 'FNA - Dhaka Carnival Meta Appliance',
    location: 'Carnival Internet AS58715, Dhaka',
    country: 'Local ISP',
    countryCode: 'FNA',
    provider: 'Meta Edge Infra / Carnival',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Dedicated Meta FNA video cache serving residential FTTH subscribers in Dhaka.',
    routingInfo: 'Intra-network fiber loop connection.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-link3-dhaka',
    name: 'FNA - Dhaka Link3 Meta Video Node',
    location: 'Link3 AS17494, Banani',
    country: 'Local ISP',
    countryCode: 'FNA',
    provider: 'Meta Edge Infra / Link3',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'High-speed caching appliance serving WhatsApp media and Facebook feeds.',
    routingInfo: 'Direct internal autonomous system peering.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-dotnet-dhaka',
    name: 'FNA - Dhaka Dot Internet Meta Cache',
    location: 'Dot Internet AS132602, Dhanmondi',
    country: 'Local ISP',
    countryCode: 'FNA',
    provider: 'Meta Edge Infra / DotNet',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Embedded caching server providing instant media delivery for South Dhaka.',
    routingInfo: 'Local ISP intra-rack connection.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-icc-dhaka',
    name: 'FNA - Dhaka ICC Communication Node',
    location: 'ICC AS58700, Uttara',
    country: 'Local ISP',
    countryCode: 'FNA',
    provider: 'Meta Edge Infra / ICC',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'North Dhaka Meta edge appliance for video playback and live streams.',
    routingInfo: 'Direct autonomous system rack connection.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-circle-dhaka',
    name: 'FNA - Dhaka Circle Network Meta Cache',
    location: 'Circle Network AS58682, Mirpur',
    country: 'Local ISP',
    countryCode: 'FNA',
    provider: 'Meta Edge Infra / Circle',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'High-density video caching node for residential broadband users.',
    routingInfo: 'Internal network cache routing.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-gp-core',
    name: 'FNA - Grameenphone Mobile Meta Edge',
    location: 'Bashundhara GP House, Dhaka',
    country: 'Local Telco',
    countryCode: 'FNA',
    provider: 'Grameenphone (AS24432)',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Primary cellular Meta FNA cluster serving 4G and 5G mobile subscribers nationwide.',
    routingInfo: 'Mobile packet core direct optical peering.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-robi-core',
    name: 'FNA - Robi Axiata Mobile Meta Edge',
    location: 'Gulshan Robi HQ, Dhaka',
    country: 'Local Telco',
    countryCode: 'FNA',
    provider: 'Robi Axiata (AS24389)',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'High-capacity mobile cache cluster for Facebook Watch and Reels media.',
    routingInfo: 'Direct telco core autonomous system interconnect.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-bl-core',
    name: 'FNA - Banglalink Mobile Meta Appliance',
    location: 'Tigers Den Banglalink, Dhaka',
    country: 'Local Telco',
    countryCode: 'FNA',
    provider: 'Banglalink (AS45246)',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Cellular caching node optimizing Instagram feeds and mobile media.',
    routingInfo: 'Direct cellular core gateway peering.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-ctg-coastal',
    name: 'FNA - Chittagong Coastal Meta Appliance',
    location: 'Chittagong Coastal Datacenter',
    country: 'Local ISP',
    countryCode: 'FNA',
    provider: 'Chittagong Broadband AS133945',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Regional Meta appliance serving port city and coastal district subscribers.',
    routingInfo: 'Direct optical peering inside Chittagong regional exchange.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-sylhet-node',
    name: 'FNA - Sylhet Regional Meta Cache',
    location: 'Sylhet Divisional Node',
    country: 'Local ISP',
    countryCode: 'FNA',
    provider: 'Sylhet Net AS135541',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Divisional video and image cache node for North-Eastern users.',
    routingInfo: 'Direct internal network peering.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-rajshahi-node',
    name: 'FNA - Rajshahi Meta Edge Appliance',
    location: 'Rajshahi Metro Node',
    country: 'Local ISP',
    countryCode: 'FNA',
    provider: 'North Bengal AS136932',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'North Bengal regional Meta edge server for local internet service providers.',
    routingInfo: 'Domestic regional rack termination.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-khulna-node',
    name: 'FNA - Khulna Metropolitan Meta Node',
    location: 'Khulna City Node',
    country: 'Local ISP',
    countryCode: 'FNA',
    provider: 'South Gate AS134812',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Regional edge appliance serving South-Western Bangladesh.',
    routingInfo: 'Local network internal interconnect.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔵',
  },
  {
    id: 'fna-kolkata-pop',
    name: 'FNA - Meta Kolkata Edge PoP',
    location: 'Kolkata Peering Exchange',
    country: 'Regional Edge',
    countryCode: 'IN',
    provider: 'Meta Edge Networks',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Overland regional Meta edge point of presence serving cross-border routes.',
    routingInfo: 'ITC terrestrial low-latency cross-border link.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'fna-mumbai-cluster',
    name: 'FNA - Meta Mumbai Edge Cluster',
    location: 'BOM Datacenter, Mumbai',
    country: 'Regional Edge',
    countryCode: 'IN',
    provider: 'Meta Platforms (AS32934)',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Major South Asian Meta infrastructure cluster with gigabit throughput.',
    routingInfo: 'Direct subsea route to Indian financial hub.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'fna-chennai-cluster',
    name: 'FNA - Meta Chennai Edge Cluster',
    location: 'MAA Datacenter, Chennai',
    country: 'Regional Edge',
    countryCode: 'IN',
    provider: 'Meta Platforms (AS32934)',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Southern India edge cluster connected directly via Bay of Bengal subsea cables.',
    routingInfo: 'Submarine cable low-hop route.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'fna-sg-tanjong',
    name: 'FNA - Meta Singapore Edge Hub 1',
    location: 'Tanjong Kling Datacenter, Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Meta Platforms (AS32934)',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Flagship Southeast Asian Meta hyperscale facility with massive bandwidth capacity.',
    routingInfo: 'Direct SMW-4 / SMW-5 submarine cable interconnect.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'fna-sg-jurong',
    name: 'FNA - Meta Singapore Edge Hub 2',
    location: 'Jurong Data Center, Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Meta Platforms (AS32934)',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Redundant Southeast Asia edge cluster handling regional media distribution.',
    routingInfo: 'Direct Singapore IXP cross-connect.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'fna-kl-pop',
    name: 'FNA - Meta Kuala Lumpur Edge Node',
    location: 'Cyberjaya, Malaysia',
    country: 'Malaysia',
    countryCode: 'MY',
    provider: 'Meta Platforms (AS32934)',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'ASEAN regional edge node delivering Instagram and WhatsApp assets.',
    routingInfo: 'Intra-ASEAN submarine fiber interconnect.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇲🇾',
  },
  {
    id: 'fna-bangkok-pop',
    name: 'FNA - Meta Bangkok Edge Node',
    location: 'Bangkok Core Datacenter, Thailand',
    country: 'Thailand',
    countryCode: 'TH',
    provider: 'Meta Platforms (AS32934)',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'Indochina regional Meta edge point of presence.',
    routingInfo: 'Regional undersea and terrestrial optical route.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇹🇭',
  },
  {
    id: 'fna-hk-cluster',
    name: 'FNA - Meta Hong Kong Edge Cluster',
    location: 'HKG Datacenter, Hong Kong',
    country: 'Hong Kong',
    countryCode: 'HK',
    provider: 'Meta Platforms (AS32934)',
    category: 'fna',
    categoryLabel: 'FNA',
    description: 'East Asian edge cluster for high-volume content caching.',
    routingInfo: 'Tier-1 subsea trans-Asia route.',
    pingUrl: metaPing,
    downloadUrl: metaDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇭🇰',
  },

  // ==========================================
  // 4. GGC (22 Google Global Cache Nodes)
  // ==========================================
  {
    id: 'ggc-amberit-dhaka',
    name: 'GGC - Dhaka AmberIT YouTube Cache',
    location: 'Mohakhali GGC Rack, Dhaka',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Google Edge Network / AmberIT',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Google Global Cache rack deployed directly inside AmberIT ISP datacenter.',
    routingInfo: 'Zero-hop local ISP internal cache serving YouTube 4K and Google Play.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-carnival-dhaka',
    name: 'GGC - Dhaka Carnival Google Edge',
    location: 'Gulshan GGC Rack, Dhaka',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Google Edge Network / Carnival',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'High-throughput Google caching server for residential broadband subscribers.',
    routingInfo: 'Intra-network optical interconnect.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-link3-dhaka',
    name: 'GGC - Dhaka Link3 Google Cache',
    location: 'Banani GGC Rack, Dhaka',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Google Edge Network / Link3',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Dedicated GGC rack serving corporate and FTTH users in central Dhaka.',
    routingInfo: 'Direct internal autonomous system peering.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-dotnet-dhaka',
    name: 'GGC - Dhaka Dot Internet Google Cache',
    location: 'Dhanmondi GGC Rack, Dhaka',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Google Edge Network / DotNet',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Embedded Google cache server providing instant YouTube and Drive streaming.',
    routingInfo: 'Local ISP intra-rack connection.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-icc-dhaka',
    name: 'GGC - Dhaka ICC YouTube Node',
    location: 'Uttara GGC Rack, Dhaka',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Google Edge Network / ICC',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'North Dhaka Google caching node handling video streams and app updates.',
    routingInfo: 'Direct autonomous system rack connection.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-circle-dhaka',
    name: 'GGC - Dhaka Circle Network Google Cache',
    location: 'Mirpur GGC Rack, Dhaka',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Google Edge Network / Circle',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'High-density video caching node for West Dhaka broadband users.',
    routingInfo: 'Internal network cache routing.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-gp-core',
    name: 'GGC - Grameenphone Mobile Google Core',
    location: 'Bashundhara GP House, Dhaka',
    country: 'Local Telco',
    countryCode: 'GGC',
    provider: 'Grameenphone (AS24432)',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Primary cellular Google Global Cache cluster serving millions of mobile data users.',
    routingInfo: 'Mobile packet core direct optical peering.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-robi-core',
    name: 'GGC - Robi Axiata Mobile Google Edge',
    location: 'Gulshan Robi HQ, Dhaka',
    country: 'Local Telco',
    countryCode: 'GGC',
    provider: 'Robi Axiata (AS24389)',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'High-capacity mobile cache cluster for YouTube video and Google Android updates.',
    routingInfo: 'Direct telco core autonomous system interconnect.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-bl-core',
    name: 'GGC - Banglalink Mobile Google Cache',
    location: 'Tigers Den Banglalink, Dhaka',
    country: 'Local Telco',
    countryCode: 'GGC',
    provider: 'Banglalink (AS45246)',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Cellular caching node optimizing YouTube streams and Google services.',
    routingInfo: 'Direct cellular core gateway peering.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-ctg-agrabad',
    name: 'GGC - Chittagong Agrabad Google Cache',
    location: 'Agrabad GGC Rack, Chittagong',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Chittagong GGC Peering',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Coastal commercial center GGC server serving port city broadband lines.',
    routingInfo: 'Direct local fiber interconnect in Chittagong.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-ctg-nasirabad',
    name: 'GGC - Chittagong Nasirabad YouTube Node',
    location: 'Nasirabad Fiber GGC, Chittagong',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Ctg Telecom GGC',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Regional GGC distribution node for North Chittagong residential ISPs.',
    routingInfo: 'Dedicated optical fiber cross-connect.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-sylhet-node',
    name: 'GGC - Sylhet Zindabazar Google Edge',
    location: 'Sylhet GGC Rack, Sylhet',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Sylhet Regional GGC',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Divisional Google cache serving streaming traffic across Sylhet region.',
    routingInfo: 'Direct regional internal network peering.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-rajshahi-node',
    name: 'GGC - Rajshahi Divisional Google Cache',
    location: 'Rajshahi GGC Rack, Rajshahi',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Rajshahi GGC Hub',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'North Bengal regional Google edge server for educational and FTTH traffic.',
    routingInfo: 'Regional internal ISP cache routing.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-khulna-node',
    name: 'GGC - Khulna Divisional Google Edge',
    location: 'Khulna GGC Rack, Khulna',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Khulna GGC Hub',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'South-Western divisional Google cache cluster.',
    routingInfo: 'Local network internal interconnect.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-barisal-node',
    name: 'GGC - Barisal Regional Google Cache',
    location: 'Barisal GGC Rack, Barisal',
    country: 'Local ISP',
    countryCode: 'GGC',
    provider: 'Barisal GGC Peering',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Southern riverine divisional YouTube and Google caching point.',
    routingInfo: 'Padma optical corridor connection.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🔴',
  },
  {
    id: 'ggc-kolkata-edge',
    name: 'GGC - Google Cloud Kolkata Edge PoP',
    location: 'CCU Edge Point, Kolkata',
    country: 'Regional Edge',
    countryCode: 'IN',
    provider: 'Google Edge Network (AS15169)',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Overland regional Google Cloud edge point of presence serving East India and Bangladesh.',
    routingInfo: 'ITC terrestrial low-latency overland optical transport.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'ggc-mumbai-datacenter',
    name: 'GGC - Google Cloud Mumbai Datacenter',
    location: 'asia-south1, Mumbai',
    country: 'Regional Edge',
    countryCode: 'IN',
    provider: 'Google Cloud Platform (AS15169)',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Tier-1 Google Cloud region hosting enterprise services, Gemini APIs and YouTube core.',
    routingInfo: 'Direct subsea route to Indian financial hub.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'ggc-delhi-edge',
    name: 'GGC - Google Cloud Delhi NCR Edge PoP',
    location: 'DEL Edge Point, Delhi',
    country: 'Regional Edge',
    countryCode: 'IN',
    provider: 'Google Cloud (AS15169)',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Northern India Google Cloud edge facility with extensive carrier peering.',
    routingInfo: 'Overland terrestrial and subsea routes.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'ggc-chennai-edge',
    name: 'GGC - Google Cloud Chennai Edge PoP',
    location: 'MAA Edge Point, Chennai',
    country: 'Regional Edge',
    countryCode: 'IN',
    provider: 'Google Cloud (AS15169)',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Bay of Bengal landing station Google Cloud edge facility.',
    routingInfo: 'Submarine cable low-latency interconnect.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'ggc-sg-jurong',
    name: 'GGC - Google Cloud Singapore Edge 1',
    location: 'asia-southeast1, Jurong',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Google Cloud (AS15169)',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Flagship Southeast Asian Google Cloud datacenter campus.',
    routingInfo: 'Direct SMW-4 / SMW-5 submarine cable landing.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'ggc-sg-lokyang',
    name: 'GGC - Google Cloud Singapore Edge 2',
    location: 'asia-southeast1, Lok Yang',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Google Cloud (AS15169)',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Redundant Singapore datacenter campus delivering high-speed Google cloud storage.',
    routingInfo: 'Direct subsea landing and peering switch.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'ggc-bangkok-pop',
    name: 'GGC - Google Cloud Bangkok Edge PoP',
    location: 'asia-southeast2, Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    provider: 'Google Cloud (AS15169)',
    category: 'ggc',
    categoryLabel: 'GGC',
    description: 'Indochina regional Google edge location for low-latency media delivery.',
    routingInfo: 'Regional subsea cable interconnect.',
    pingUrl: googlePing,
    downloadUrl: googleDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇹🇭',
  },

  // ==========================================
  // 5. CDN (22 Global Anycast CDN Nodes)
  // ==========================================
  {
    id: 'cdn-cf-dhaka',
    name: 'CDN - Cloudflare Anycast Dhaka Edge (DAC)',
    location: 'Dhaka BDIX Interconnect, Bangladesh',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Cloudflare Inc. (AS13335)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Cloudflares local Anycast PoP situated directly inside the Dhaka internet exchange.',
    routingInfo: 'BGP Anycast routing directly terminated inside Bangladesh.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '⚡',
  },
  {
    id: 'cdn-cf-ctg',
    name: 'CDN - Cloudflare Anycast Chittagong Edge (CGP)',
    location: 'Chittagong Coastal PoP, Bangladesh',
    country: 'Bangladesh',
    countryCode: 'BD',
    provider: 'Cloudflare Inc. (AS13335)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Coastal edge point of presence delivering ultra-low latency for southern users.',
    routingInfo: 'Local Anycast edge routing in Chittagong.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '⚡',
  },
  {
    id: 'cdn-cf-kolkata',
    name: 'CDN - Cloudflare Kolkata Edge PoP (CCU)',
    location: 'Kolkata Anycast Datacenter',
    country: 'India',
    countryCode: 'IN',
    provider: 'Cloudflare Inc. (AS13335)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Nearest international Cloudflare edge datacenter reached via overland optical links.',
    routingInfo: 'Terrestrial ITC low-ping routing.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '⚡',
  },
  {
    id: 'cdn-cf-singapore',
    name: 'CDN - Cloudflare Singapore Mega Edge (SIN)',
    location: 'Singapore Equinix Core',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Cloudflare Inc. (AS13335)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Massive multi-terabit Anycast datacenter routing Southeast Asian internet traffic.',
    routingInfo: 'Submarine cable SMW-4 / SMW-5 high-throughput pipe.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'cdn-cf-mumbai',
    name: 'CDN - Cloudflare Mumbai Core Edge (BOM)',
    location: 'Mumbai Datacenter Cluster',
    country: 'India',
    countryCode: 'IN',
    provider: 'Cloudflare Inc. (AS13335)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Western India primary Cloudflare Anycast routing cluster.',
    routingInfo: 'High-speed Indian national backbone transit.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'cdn-cf-chennai',
    name: 'CDN - Cloudflare Chennai Core Edge (MAA)',
    location: 'Chennai Subsea Datacenter',
    country: 'India',
    countryCode: 'IN',
    provider: 'Cloudflare Inc. (AS13335)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Southern India primary Anycast PoP connected directly to submarine cables.',
    routingInfo: 'Bay of Bengal subsea optical link.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'cdn-cf-bangkok',
    name: 'CDN - Cloudflare Bangkok Anycast (BKK)',
    location: 'Bangkok Core PoP, Thailand',
    country: 'Thailand',
    countryCode: 'TH',
    provider: 'Cloudflare Inc. (AS13335)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Indochina regional Cloudflare edge location.',
    routingInfo: 'Regional subsea and overland optical route.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇹🇭',
  },
  {
    id: 'cdn-cf-kl',
    name: 'CDN - Cloudflare Kuala Lumpur Anycast (KUL)',
    location: 'Kuala Lumpur Metro PoP, Malaysia',
    country: 'Malaysia',
    countryCode: 'MY',
    provider: 'Cloudflare Inc. (AS13335)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Peninsular Malaysia Anycast edge point of presence.',
    routingInfo: 'Intra-ASEAN submarine transit.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇲🇾',
  },
  {
    id: 'cdn-fastly-sg',
    name: 'CDN - Fastly Edge Singapore',
    location: 'Fastly SIN PoP, Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Fastly Inc. (AS54113)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'High-throughput SSD edge cloud platform with extensive peering in Asia-Pacific.',
    routingInfo: 'BGP Anycast routing to regional Fastly Shield and Edge.',
    pingUrl: 'https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js',
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'cdn-fastly-mumbai',
    name: 'CDN - Fastly Edge Mumbai',
    location: 'Fastly BOM PoP, Mumbai',
    country: 'India',
    countryCode: 'IN',
    provider: 'Fastly Inc. (AS54113)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'South Asian Fastly edge cluster delivering dynamic HTTP/3 acceleration.',
    routingInfo: 'Direct subsea and terrestrial DWDM interconnection.',
    pingUrl: 'https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js',
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'cdn-fastly-chennai',
    name: 'CDN - Fastly Edge Chennai',
    location: 'Fastly MAA PoP, Chennai',
    country: 'India',
    countryCode: 'IN',
    provider: 'Fastly Inc. (AS54113)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Southern Indian Fastly edge PoP for ultra-fast asset caching.',
    routingInfo: 'Bay of Bengal submarine fiber transit.',
    pingUrl: 'https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js',
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'cdn-fastly-tokyo',
    name: 'CDN - Fastly Anycast Tokyo Mega PoP',
    location: 'Fastly HND PoP, Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    provider: 'Fastly Inc. (AS54113)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'East Asian flagship edge location with massive multi-terabit edge capacity.',
    routingInfo: 'Trans-Asia Pacific subsea optical routing.',
    pingUrl: 'https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js',
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇯🇵',
  },
  {
    id: 'cdn-aws-mumbai',
    name: 'CDN - AWS CloudFront Edge Mumbai (BOM50)',
    location: 'Amazon Web Services Edge, Mumbai',
    country: 'India',
    countryCode: 'IN',
    provider: 'Amazon CloudFront (AS16509)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Amazon global content delivery network edge location in Western India.',
    routingInfo: 'AWS global private backbone network transit.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'cdn-aws-chennai',
    name: 'CDN - AWS CloudFront Edge Chennai (MAA50)',
    location: 'AWS CloudFront PoP, Chennai',
    country: 'India',
    countryCode: 'IN',
    provider: 'Amazon CloudFront (AS16509)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Amazon CloudFront edge location connecting Bay of Bengal subsea routes.',
    routingInfo: 'AWS private optical network cross-connect.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'cdn-aws-singapore',
    name: 'CDN - AWS CloudFront Edge Singapore (SIN50)',
    location: 'AWS CloudFront PoP, Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Amazon CloudFront (AS16509)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Southeast Asia flagship CloudFront edge location with petabyte capacity.',
    routingInfo: 'Submarine cable direct landing at AWS private core.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'cdn-akamai-sg',
    name: 'CDN - Akamai EdgeSuite Singapore Core',
    location: 'Akamai Hub, Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Akamai Technologies (AS20940)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Akamais largest edge deployment in ASEAN distributing enterprise traffic.',
    routingInfo: 'Direct peering with Southeast Asian submarine cables.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
  {
    id: 'cdn-akamai-mumbai',
    name: 'CDN - Akamai EdgeSuite Mumbai Datacenter',
    location: 'Akamai India Cluster, Mumbai',
    country: 'India',
    countryCode: 'IN',
    provider: 'Akamai Technologies (AS20940)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Major South Asian Akamai edge cluster powering live sports and OTT video.',
    routingInfo: 'Tier-1 carrier backbone connection.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇮🇳',
  },
  {
    id: 'cdn-bunny-sg',
    name: 'CDN - BunnyCDN Anycast Singapore Tier-1',
    location: 'Bunny High-Speed Edge, Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'BunnyWay d.o.o.',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Ultra-low latency next-generation Anycast edge cloud and video delivery network.',
    routingInfo: 'Direct Tier-1 carrier transit in Singapore.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🐰',
  },
  {
    id: 'cdn-bunny-mumbai',
    name: 'CDN - BunnyCDN Anycast Mumbai Tier-1',
    location: 'Bunny South Asia Edge, Mumbai',
    country: 'India',
    countryCode: 'IN',
    provider: 'BunnyWay d.o.o.',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Tier-1 South Asian edge PoP delivering instant static and media assets.',
    routingInfo: 'High-speed Indian peering fabric.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🐰',
  },
  {
    id: 'cdn-jsdelivr',
    name: 'CDN - jsDelivr Worldwide Open-Source CDN',
    location: 'Multi-CDN Global Anycast',
    country: 'Global Nearest',
    countryCode: 'GLOBAL',
    provider: 'jsDelivr / Multi-CDN',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Multi-provider CDN combining Cloudflare, Fastly, and Bunny for open-source assets.',
    routingInfo: 'Smart DNS routing to the highest-performing regional PoP.',
    pingUrl: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js',
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🌐',
  },
  {
    id: 'cdn-cdnjs',
    name: 'CDN - cdnjs Cloudflare Global Accelerator',
    location: 'Global Anycast Edge Network',
    country: 'Global Nearest',
    countryCode: 'GLOBAL',
    provider: 'cdnjs / Cloudflare',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Accelerated CDN serving libraries from hundreds of global edge nodes.',
    routingInfo: 'Nearest Anycast node routing.',
    pingUrl: 'https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js',
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '⚡',
  },
  {
    id: 'cdn-azure-sg',
    name: 'CDN - Microsoft Azure Edge Singapore (SIN20)',
    location: 'Azure Front Door PoP, Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    provider: 'Microsoft Corporation (AS8075)',
    category: 'global_cdn',
    categoryLabel: 'CDN',
    description: 'Microsoft global Anycast edge providing high-speed cloud acceleration.',
    routingInfo: 'Microsoft global private fiber optic backbone.',
    pingUrl: cfPing,
    downloadUrl: cfDown,
    uploadUrl: cfUp,
    isCustom: false,
    flag: '🇸🇬',
  },
];

export function getCustomServers(): SpeedTestServer[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY_CUSTOM_SERVERS);
    if (!raw) return [];
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

export function saveCustomServer(server: {
  id?: string;
  name: string;
  location: string;
  country?: string;
  category: NetworkCategory;
  provider?: string;
  pingUrl: string;
  downloadBaseUrl: string;
  uploadUrl: string;
}): SpeedTestServer {
  const categoryMeta = NETWORK_CATEGORIES.find((c) => c.id === server.category);
  const categoryLabel = categoryMeta ? categoryMeta.name : 'Custom Node';

  const newServer: SpeedTestServer = {
    id: server.id || `custom-${Date.now()}`,
    name: server.name,
    location: server.location,
    country: server.country || 'Custom',
    countryCode: 'USR',
    provider: server.provider || 'Custom Dedicated Server',
    category: server.category,
    categoryLabel: categoryLabel,
    description: `Custom node for ${categoryLabel} measurement.`,
    pingUrl: server.pingUrl,
    downloadUrl: (bytes: number) => {
      try {
        const url = new URL(server.downloadBaseUrl, window.location.href);
        url.searchParams.set('bytes', String(bytes));
        return url.toString();
      } catch {
        return server.downloadBaseUrl;
      }
    },
    uploadUrl: server.uploadUrl,
    isCustom: true,
    flag: '🛠️',
  };

  const existing = getCustomServers();
  const filtered = existing.filter((s) => s.id !== newServer.id);
  const updated = [...filtered, newServer];

  localStorage.setItem(STORAGE_KEY_CUSTOM_SERVERS, JSON.stringify(updated));
  return newServer;
}

export function deleteCustomServer(id: string): void {
  const existing = getCustomServers();
  const filtered = existing.filter((s) => s.id !== id);
  localStorage.setItem(STORAGE_KEY_CUSTOM_SERVERS, JSON.stringify(filtered));
}

export function getAllServers(): SpeedTestServer[] {
  const custom = getCustomServers();
  return [...DEFAULT_SERVERS, ...custom];
}

export function getActiveServer(): SpeedTestServer {
  const all = getAllServers();
  const savedId = localStorage.getItem(STORAGE_KEY_SELECTED_SERVER);
  if (savedId) {
    const found = all.find((s) => s.id === savedId);
    if (found) return found;
  }
  return all[0];
}

export function setActiveServerId(id: string): void {
  localStorage.setItem(STORAGE_KEY_SELECTED_SERVER, id);
}

export const setSelectedServerId = setActiveServerId;

export function getServersByCategory(category: NetworkCategory): SpeedTestServer[] {
  const all = getAllServers();
  return all.filter((s) => s.category === category);
}
